# Generated by Django 3.2.15 on 2023-07-19 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=255, verbose_name='模板名称')),
                ('business_name', models.IntegerField(choices=[(0, '小游戏教学演示')], verbose_name='业务名称')),
                ('template_type', models.IntegerField(choices=[(0, '变更发布'), (1, '扩缩类'), (2, '上线类'), (3, '下架类'), (4, '例行维护')], verbose_name='模板类型')),
                ('operator_id', models.CharField(max_length=255, verbose_name='操作识别号')),
                ('person_couldOperate', models.CharField(max_length=255, verbose_name='可操作者')),
                ('creator', models.CharField(max_length=255, verbose_name='创建者')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('STATE', models.IntegerField(choices=[(1, '待操作'), (2, '操作中'), (3, '完成')], default=1, verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=255, verbose_name='模板名称')),
                ('business_name', models.IntegerField(choices=[(0, '小游戏教学演示')], verbose_name='业务名称')),
                ('template_type', models.IntegerField(choices=[(0, '变更发布'), (1, '扩缩类'), (2, '上线类'), (3, '下架类'), (4, '例行维护')], verbose_name='模板类型')),
                ('creator', models.CharField(max_length=255, verbose_name='创建者')),
                ('updator', models.CharField(max_length=255, verbose_name='更新者')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateContents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='序号')),
                ('operation', models.CharField(max_length=255, verbose_name='操作事项')),
                ('operation_note', models.CharField(max_length=255, verbose_name='备注')),
                ('person_responsible', models.CharField(max_length=128, verbose_name='负责人')),
                ('belong_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_application.templates')),
            ],
        ),
        migrations.CreateModel(
            name='JobContents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='序号')),
                ('operation', models.CharField(max_length=255, verbose_name='操作事项')),
                ('operation_note', models.CharField(max_length=255, verbose_name='备注')),
                ('finish_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='完成时间')),
                ('person_responsible', models.CharField(max_length=128, verbose_name='负责人')),
                ('person_confirm', models.CharField(default='', max_length=128, verbose_name='确认人')),
                ('state', models.BooleanField(default=False, verbose_name='是否完成')),
                ('belong_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_application.jobs')),
            ],
        ),
    ]
